'''
You are given two strings s and t.
String t is generated by random shuffling string s and then add one more letter at a random position.
Return the letter that was added to t.

Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:
Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
'''

def findTheDifference(s: str, t: str) -> str:
    my_map = {}
    for letter in s:
        if letter in my_map:
            my_map[letter]+=1
        else:
            my_map[letter]=1
    for letter in t:
        if letter in my_map and my_map[letter] > 0:
            my_map[letter]-=1
        else: return letter